[tools]
bun = "latest"
go = "latest"
node = "lts"
task = "latest"
pnpm = "latest"
buf = "latest"
helm = "latest"
kubectl = "latest"
tilt = "latest"
terragrunt = "latest"
opentofu = "latest"
rust = "stable"
"cargo:lq" = "latest"
